server:
  port: 5555
spring:
  application:
    name: zuulServer
  profiles:
    active: default
  cloud:
    config:
      enable: true
management:
  endpoints:
    web:
      exposure:
        include: "env,refresh,routes"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  ignored-services: '*'
  routes:
    organizationService: /organization/**
    licensingService: /licensing/**
  sensitive-headers: Cookie,Set-Cookie
signing:
  key: secret