server:
  port: 8901
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "{cipher}761c77f4b9567f088353f195369ae3443bf855a049656141bf32a18be23d7a54758fc47b0e1158116fa5627b9faa6c95b1b245c6c668046fb64784e0cfd344a7"
    username: study
    password: "{cipher}4ee6798692272b91dafd87eed35ed4898e7f4b2ee48dec564cd8b6cf350ebc81"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: authenticationService
  profile:
    active: default
  cloud:
    config:
      enable: true
management:
  endpoints:
    web:
      exposure:
        include: "env,refresh"
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
signing:
  key: secret